name: 'Build & Test'

on: [push, pull_request_target]

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Prepare Release
        if: runner.os == 'Linux'
        run: |
          echo "Release!!!"
          npm run build:zip

      - name: Publish Release
        if: runner.os == 'Linux' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          body: "See [CHANGELOG.md](https://github.com/jhildenbiddle/typora-themeable/blob/main/CHANGELOG.md) for details"
          files: dist/typora-themeable.zip
